"""One-time script that generates backend/templates/violation_report_template.docx —
the docxtpl Jinja template consumed by docx_report.py (Section 9).

Run once: `python -m backend.reporting.build_template`
Re-run only if the report layout itself needs to change; the generated .docx
is checked in like any other template asset afterwards.
"""
from __future__ import annotations

import os

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "..", "templates", "violation_report_template.docx")


def build_template(output_path: str = TEMPLATE_PATH) -> str:
    doc = Document()

    title = doc.add_heading("Cartage Contractor Performance — Violation Summary", level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta.add_run("Contractor: ").bold = True
    meta.add_run("{{ contractor_name }} ({{ cc_number }})")

    period = doc.add_paragraph()
    period.add_run("Evaluation period: ").bold = True
    period.add_run("{{ period }}")

    score_p = doc.add_paragraph()
    score_p.add_run("Overall Score: ").bold = True
    run = score_p.add_run("{{ overall_score }}%")
    run.font.size = Pt(14)
    run.bold = True

    doc.add_paragraph(
        "This contractor scored below the 80% compliance threshold for the period above. "
        "The category breakdown below shows the incident count and resulting score "
        "contribution for each evaluated category. Contractors scoring below 80% are "
        "required to submit a corrective action plan within 15 working days of receipt "
        "of this report."
    )

    doc.add_heading("Category Breakdown", level=2)

    # docxtpl's {%tr %} row-loop tag must sit alone in its own dedicated row —
    # the "for" tag row, then the repeated data row(s), then a separate
    # "endfor" tag row (confirmed against docxtpl's own dynamic_table test
    # fixture; embedding for/endfor in the same data row silently drops it).
    table = doc.add_table(rows=4, cols=3)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text = "Category"
    hdr[1].text = "Incident Count"
    hdr[2].text = "Score Contribution"

    table.rows[1].cells[0].text = "{%tr for cat in categories %}"

    body_row = table.rows[2].cells
    body_row[0].text = "{{ cat.name }}"
    body_row[1].text = "{{ cat.count }}"
    body_row[2].text = "{{ cat.score }}%"

    table.rows[3].cells[0].text = "{%tr endfor %}"

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.add_run(
        "This is an automated report generated by the Cartage Contractor "
        "Performance Evaluation system. Direct questions to the Fleet Compliance team."
    ).italic = True

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc.save(output_path)
    return output_path


if __name__ == "__main__":
    path = build_template()
    print(f"Template written to {path}")
